/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';

/**
* A header with a search box and one dropdown on the left and one on  the right. 
* In order to turn the dropdowns into a working navigation menu, configure each dropdown item's
* Router Link Destination with a component in your app and make sure that your app has a Router
* Outlet.
*/
@Component({
  selector: 'app-header-with-search-and-2-dropdowns',
  standalone: true,
  templateUrl: './header-with-search-and-2-dropdowns.component.html',
  styleUrls: ['./header-with-search-and-2-dropdowns.component.scss'],
  imports: [NgbDropdownModule, RouterLink, CommonModule]
})
export class HeaderWithSearchAnd2DropdownsComponent {

  constructor() {}

  public onHyperlink1Click($event: MouseEvent): void {
    $event.preventDefault();
  }

  public onHyperlink2Click($event: MouseEvent): void {
    $event.preventDefault();
  }
}
