/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbDropdownModule, NgbNavModule } from '@ng-bootstrap/ng-bootstrap';

/**
* A header with navigation links, a search box and a dropdown menu on the right.
* In order to turn the dropdown and navigation links into a working navigation menu, configure each
* item's Router Link Destination with a component in your app and make sure that your app has a Router
* Outlet.
*/
@Component({
  selector: 'app-header-with-search-and-dropdown-menu',
  standalone: true,
  templateUrl: './header-with-search-and-dropdown-menu.component.html',
  styleUrls: ['./header-with-search-and-dropdown-menu.component.scss'],
  imports: [RouterLink, NgbNavModule, NgbDropdownModule, CommonModule]
})
export class HeaderWithSearchAndDropdownMenuComponent {

  constructor() {}

  public onHyperlink7Click($event: MouseEvent): void {
    $event.preventDefault();
  }
}
