/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbDropdownModule, NgbNavModule } from '@ng-bootstrap/ng-bootstrap';

/**
* A narrow Sidebar that uses icons for navigation and has a dropdown menu at the bottom.
* In order to turn the Sidebar into a working navigation menu, configure each nav link 's or dropdown
* item's Router Link Destination with a component in your app and make sure that your app has a Router
* Outlet.

*/
@Component({
  selector: 'app-icons-only-sidebar',
  standalone: true,
  templateUrl: './icons-only-sidebar.component.html',
  styleUrls: ['./icons-only-sidebar.component.scss'],
  imports: [NgbNavModule, RouterLink, NgbDropdownModule, CommonModule]
})
export class IconsOnlySidebarComponent {

  constructor() {}

  public onHyperlink7Click($event: MouseEvent): void {
    $event.preventDefault();
  }
}
