/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

/**
* A simple responsive Bootstrap Grid with each column containing an icon, title, explainer and call to
* action link.
*/
@Component({
  selector: 'app-columns-with-icons',
  standalone: true,
  templateUrl: './columns-with-icons.component.html',
  styleUrls: ['./columns-with-icons.component.scss'],
  imports: [CommonModule]
})
export class ColumnsWithIconsComponent {

  constructor() {}
}
