/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

/**
* A responsive grid of Bootstrap Cards. Each card has a background image and custom content that
* demonstrates different Bootstrap utilities for borders, display, spacing and alignment.
*/
@Component({
  selector: 'app-custom-cards',
  standalone: true,
  templateUrl: './custom-cards.component.html',
  styleUrls: ['./custom-cards.component.scss'],
  imports: [CommonModule]
})
export class CustomCardsComponent {

  constructor() {}
}
