/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

/**
* A 2-column Bootstrap Grid with a primary title on the left and nested columns on the right, each
* containing an icon, title and summary.
*/
@Component({
  selector: 'app-features-with-title',
  standalone: true,
  templateUrl: './features-with-title.component.html',
  styleUrls: ['./features-with-title.component.scss'],
  imports: [CommonModule]
})
export class FeaturesWithTitleComponent {

  constructor() {}
}
