/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

/**
* A Bootstrap Grid with each column containing an icon on the left and a title, summary and action
* button on the right.
*/
@Component({
  selector: 'app-hanging-icons',
  standalone: true,
  templateUrl: './hanging-icons.component.html',
  imports: [CommonModule]
})
export class HangingIconsComponent {

  constructor() {}
}
