/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { Routes } from '@angular/router';
import { AppComponent } from './app.component';
import { _FeaturesComponent } from './components/Features/_-features.component';
import { ColumnsWithIconsComponent } from './components/Features/columns-with-icons.component';
import { CustomCardsComponent } from './components/Features/custom-cards.component';
import { FeaturesWithTitleComponent } from './components/Features/features-with-title.component';
import { HangingIconsComponent } from './components/Features/hanging-icons.component';
import { IconGridComponent } from './components/Features/icon-grid.component';
import { _FootersComponent } from './components/Footers/_-footers.component';
import { FooterWithLinkSectionsAndNewsletterSignupComponent } from './components/Footers/footer-with-link-sections-and-newsletter-signup.component';
import { FooterWithLinkSectionsComponent } from './components/Footers/footer-with-link-sections.component';
import { SimpleFooterWithSocialLinksComponent } from './components/Footers/simple-footer-with-social-links.component';
import { SimpleFooterComponent } from './components/Footers/simple-footer.component';
import { SimpleTwoRowFooterComponent } from './components/Footers/simple-two-row-footer.component';
import { _HeadersComponent } from './components/Headers/_-headers.component';
import { DarkHeaderWithSearchAndLoginComponent } from './components/Headers/dark-header-with-search-and-login.component';
import { DoubleHeaderWithMenuIconsComponent } from './components/Headers/double-header-with-menu-icons.component';
import { DoubleHeaderWithSearchAndLoginComponent } from './components/Headers/double-header-with-search-and-login.component';
import { HeaderWithLoginButtonsComponent } from './components/Headers/header-with-login-buttons.component';
import { HeaderWithSearchAnd2DropdownsComponent } from './components/Headers/header-with-search-and-2-dropdowns.component';
import { HeaderWithSearchAndDropdownMenuComponent } from './components/Headers/header-with-search-and-dropdown-menu.component';
import { SimpleHeaderWithLogoComponent } from './components/Headers/simple-header-with-logo.component';
import { SimpleResponsiveHeaderComponent } from './components/Headers/simple-responsive-header.component';
import { _SidebarsComponent } from './components/Sidebars/_-sidebars.component';
import { CollapsibleSidebarComponent } from './components/Sidebars/collapsible-sidebar.component';
import { DarkSidebarComponent } from './components/Sidebars/dark-sidebar.component';
import { IconsOnlySidebarComponent } from './components/Sidebars/icons-only-sidebar.component';
import { LightSidebarComponent } from './components/Sidebars/light-sidebar.component';
import { SidebarWithListGroupComponent } from './components/Sidebars/sidebar-with-list-group.component';

export const routes: Routes = [
  {
    path: 'app',
    component: AppComponent
  },
  {
    path: 'features',
    component: _FeaturesComponent,
    children: [
      {
        path: 'columns-with-icons',
        component: ColumnsWithIconsComponent
      },
      {
        path: 'hanging-icons',
        component: HangingIconsComponent
      },
      {
        path: 'custom-cards',
        component: CustomCardsComponent
      },
      {
        path: 'icon-grid',
        component: IconGridComponent
      },
      {
        path: 'features-with-title',
        component: FeaturesWithTitleComponent
      },
      {
        path: '',
        redirectTo: 'columns-with-icons',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: 'headers',
    component: _HeadersComponent,
    children: [
      {
        path: 'dark-header-with-search-and-login',
        component: DarkHeaderWithSearchAndLoginComponent
      },
      {
        path: 'double-header-with-menu-icons',
        component: DoubleHeaderWithMenuIconsComponent
      },
      {
        path: 'double-header-with-search-and-login',
        component: DoubleHeaderWithSearchAndLoginComponent
      },
      {
        path: 'header-with-login-buttons',
        component: HeaderWithLoginButtonsComponent
      },
      {
        path: 'header-with-search-and-2-dropdowns',
        component: HeaderWithSearchAnd2DropdownsComponent
      },
      {
        path: 'header-with-search-and-dropdown-menu',
        component: HeaderWithSearchAndDropdownMenuComponent
      },
      {
        path: 'simple-header-with-logo',
        component: SimpleHeaderWithLogoComponent
      },
      {
        path: 'simple-responsive-header',
        component: SimpleResponsiveHeaderComponent
      },
      {
        path: '',
        redirectTo: 'dark-header-with-search-and-login',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '_-sidebars',
    component: _SidebarsComponent,
    children: [
      {
        path: 'dark-sidebar',
        component: DarkSidebarComponent
      },
      {
        path: 'light-sidebar',
        component: LightSidebarComponent
      },
      {
        path: 'icons-only-sidebar',
        component: IconsOnlySidebarComponent
      },
      {
        path: 'sidebar-with-list-group',
        component: SidebarWithListGroupComponent
      },
      {
        path: 'collapsible-sidebar',
        component: CollapsibleSidebarComponent
      },
      {
        path: '',
        redirectTo: 'dark-sidebar',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '_-footers',
    component: _FootersComponent,
    children: [
      {
        path: 'simple-footer',
        component: SimpleFooterComponent
      },
      {
        path: 'simple-footer-with-social-links',
        component: SimpleFooterWithSocialLinksComponent
      },
      {
        path: 'simple-two-row-footer',
        component: SimpleTwoRowFooterComponent
      },
      {
        path: 'footer-with-link-sections',
        component: FooterWithLinkSectionsComponent
      },
      {
        path: 'footer-with-link-sections-and-newsletter-signup',
        component: FooterWithLinkSectionsAndNewsletterSignupComponent
      },
      {
        path: '',
        redirectTo: 'simple-footer',
        pathMatch: 'full'
      }
    ]
  },
  {
    path: '',
    redirectTo: '/features',
    pathMatch: 'full'
  }
];
