/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

/**
* This component supports navigating the fragments in this project and is hidden from the JitBlox
* toolbox.
*/
@Component({
  selector: 'app-_-footers',
  standalone: true,
  templateUrl: './_-footers.component.html',
  styleUrls: ['./_-footers.component.scss'],
  imports: [RouterLink, RouterLinkActive, RouterOutlet, CommonModule]
})
export class _FootersComponent {

  constructor() {}
}
