/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Bootstrap fragments, at
* https://www.jitblox.com/project/ydc6cYCqVz/bootstrap-fragments
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

/**
* A basic footer with a company name, logo and some social links.
*/
@Component({
  selector: 'app-simple-footer-with-social-links',
  standalone: true,
  templateUrl: './simple-footer-with-social-links.component.html',
  imports: [CommonModule]
})
export class SimpleFooterWithSocialLinksComponent {

  constructor() {}
}
